FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y graphviz && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN python -m pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p results uploads logs

EXPOSE 8000

CMD ["uvicorn", "backend_api.http.main:app", "--host", "0.0.0.0", "--port", "8000"]
